### ISSUE TITLE
[FEATURE REQUEST] Include a parameter to disable the console logs

### ISSUE THREAD

**Issue by iec989** [Juicetan/mickdragger#1]
It was great! It is exactly what I needed - I think IT would be great if there would be a parameter to disable the console logs.

**Comment by Juicetan** [comment]
glad to hear its helped someone out.  sorry about the console logs, that was me being lazy.  I will make it silent by default and have a flag for verbosity to turn logs on.

**Comment by iec989** [comment]
@Juicetan - can you merge my request please? https://github.com/Juicetan/mickdragger/pull/2

Thanks!

**Comment by iec989** [comment]
Updated @Juicetan 

Request #2 

Please pull! Is there anything else needed for the npm package to be updated?

**Comment by iec989** [comment]
@Juicetan 
Hey buddy

any chance you could publish the changes?

Thanks
